### ISSUE TITLE
你好, 能添加文字在图片上么  依然可以拖动...

### ISSUE THREAD

**Issue by badboy-tian** [nimengbo/StickerView#5]
如题

**Comment by nimengbo** [comment]
哦，这个我有，只是没放上来…这几天较忙，没看，不好意思…

**Comment by badboy-tian** [comment]
你好, 请问能把添加文字的stickerView发给我一下么  急用 非常感谢! 邮箱 tqj.zyy@gmail.com

**Comment by nimengbo** [comment]
会在近期开源。

**Comment by badboy-tian** [comment]
好的 谢谢

2015-10-29 10:32 GMT+08:00 Abner notifications@github.com:
