### ISSUE TITLE
BubbleTextView报错!

### ISSUE THREAD

**Issue by badboy-tian** [nimengbo/StickerView#6]
你好, 用你提供的那个图片,没问题, 我换了一个自己的图片就处问题了
报错信息:
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime: java.lang.NegativeArraySizeException: -21
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at net.mwplay.gifmaker.view.BubbleTextView.autoSplit(BubbleTextView.java:788)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at net.mwplay.gifmaker.view.BubbleTextView.onDraw(BubbleTextView.java:259)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.draw(View.java:14465)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13362)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13404)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.draw(View.java:14182)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.draw(View.java:14468)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13362)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13404)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.draw(View.java:14182)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13357)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13404)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.draw(View.java:14182)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13357)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13404)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.draw(View.java:14182)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13357)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13404)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.draw(View.java:14182)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.draw(View.java:14468)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.widget.FrameLayout.draw(FrameLayout.java:472)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13362)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.View.getDisplayList(View.java:13404)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:544)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-29 12:26:58.185 9549-9549/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-29 12:27:00.113 9584-9584/? E/dalvikvm: Could not find class 'com.squareup.okhttp.OkHttpClient', referenced from method cn.bmob.v3.requestmanager.thing.<init>
10-29 12:27:00.377 9584-9584/? E/OpenGLRenderer: Getting MAX_TEXTURE_SIZE from GradienCache
10-29 12:27:00.381 9584-9584/? E/OpenGLRenderer: MAX_TEXTURE_SIZE: 16384
10-29 12:27:00.385 9584-9584/? E/OpenGLRenderer: Getting MAX_TEXTURE_SIZE from Caches::initConstraints()
10-29 12:27:00.389 9584-9584/? E/OpenGLRenderer: MAX_TEXTURE_SIZE: 16384

图片如下:
![image](https://cloud.githubusercontent.com/assets/2835129/10818396/2d46a974-7e7c-11e5-9d15-f8e81da2ff7e.png)

**Comment by nimengbo** [comment]
没出错啊，我试了下，你改了什么？我的788行是个大括号，应该是你加了什么导致的问题
