### ISSUE TITLE
Loading bitmap of custom size 

### ISSUE THREAD

**Issue by taimur97** [nimengbo/StickerView#8]
When I load a bitmap it resizes it 
How can I load a resized sticker  say like 150px by 180px? 
I tried changing the layout params from match_parent to different sizes but it didn't work and I also tried scalling the bitmap before loading it in StickerView but StickerView resizes it
Please help...

**Comment by nimengbo** [comment]
set the initScale

**Comment by imran-samed** [comment]
Just set the value of **initScale** 
In my case it was **2.8666f** and i want reduce the size of sticker
so i decrease the value by **1.5f**
And its perfect.


you can find this value in **StickerView** --> **setBitmap**
